apiVersion: extensions/v1beta1
kind: Deployment
metadata:

  name: tf-model
  namespace: default
spec:
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
        - name: model
          image: megachucky/car-sensor-model:latest
          imagePullPolicy: Always
          command: ["python3"]
          args: ["cardata-v2.py", "kafka.operator.svc.cluster.local:9071", "SENSOR_DATA_S_AVRO", "0", "model-predictions"]